### PR TITLE
feat(quic): support logical stream id

### PR DESCRIPTION
**Pull request by qzhuyan**
We need logic stream. The QUIC stream id is not transparent to the user that user is not free to choice the stream id while create the stream, thus we need logical stream to present the 'session stream' persistency.
If the QUIC stream is closed or aborted, the logical stream could be kept alive by starting new stream where both endpoints exchange the logic stream id in the stream header. This is not done yet but written in mqtt-next spec.

### CODE REVIEW

**Comment by zmstone** [comment]
make sense to add a topic -> stream ID mapping callback ?
or by default creates two streams, 0, and 1, then the callback can return 0 or 1.

**Comment by qzhuyan** [comment]
We could have the callback, but mapping topic to stream isn't the only usecase. 

In short, we need logic stream anyway. The QUIC stream id is not transparent to the user that user is not free to choice the stream id while create the stream, thus we need logical stream to present the 'session stream' persistency.  

If the QUIC stream is closed or aborted, the logical stream could be kept alive by starting new stream where both endpoints exchange the logic stream id in the stream header. This is not done yet but written in mqtt-next spec.

**Review by thalesmg — APPROVED** [review]
Is it possible to add some tests to display how to use?

**Comment by qzhuyan** [comment]
> Is it possible to add some tests to display how to use?

yes!  urgently need this get merged for this https://github.com/emqx/emqtt-bench/pull/202

**Pull request merged**
