### PR TITLE
Update cowlib dependency and add emqx_utils to rebar

### PR DESCRIPTION
**Pull request by jadercorrea**
This commit aims to fix the compilation errors related to cowlib and emqx_utils dependencies. Specifically, the changes include:

- Upgraded the cowlib dependency from version 2.11.0 to 2.12.1 to align with the requirement specified in cowboy's rebar.config.
- Added the path for emqx_utils in the rebar.config file, resolving the build problem where emqx_utils was not being fetched.
- Included build and test case badges in README.md to enhance project information.

### CODE REVIEW

**Comment by id** [comment]
Thanks @jadercorrea .

Looks like we need to include `emqx_durable_storage` in the deps as well.

**Comment by jadercorrea** [comment]
> Thanks @jadercorrea .
> 
> Looks like we need to include `emqx_durable_storage` in the deps as well.

@id Thanks for the review. Just added `emqx_durable_storage` to deps as needed.

**Comment by jadercorrea** [comment]
When reading the logs of the failing check above it seems like the skipped tests are failing the job. Seems like some experimentation on a ubuntu 20.04 container is necessary to troubleshoot.

```
Testing lib.emqtt: TEST COMPLETE, 59 ok, 0 failed, 327 skipped of 386 test cases

EXPERIMENTAL: Writing retry specification at /__w/emqtt/emqtt/_build/test/logs/retry.spec
              call rebar3 ct with '--retry' to re-run failing cases.
Updating /__w/emqtt/emqtt/_build/test/logs/index.html ... done
Updating /__w/emqtt/emqtt/_build/test/logs/all_runs.html ... done
===> Failures occurred running tests: 327
```

**Comment by qzhuyan** [comment]
pls rebase onto latest master

**Comment by qzhuyan** [comment]
thanks for the PR!

**Pull request merged**
