### PR TITLE
Use required cowlib version 2.12.1

### PR DESCRIPTION
**Pull request by amos-kibet**
Aims to resolve this error when compiling emqtt:
image

### CODE REVIEW

**Comment by zmstone** [comment]
there is still a compatibility issue to be resolved first.
see more information here:  https://github.com/emqx/emqtt/pull/221

it would be great if we can support both `gun` 1.3 and 2.x.

**Comment by rhblind** [comment]
Hi, since #221 has been merged, is there any chance this issue can be resolved? 
I'm building a library which depends on `emqtt` but cannot publish to hex because of the dependency resolution fails.

**Comment by zmstone** [comment]
cowlib was upgraded to 2.12.1 in this PR https://github.com/emqx/emqtt/pull/209

**Comment by zmstone** [comment]
Hi @rhblind 
cowlib is already on 2.12.1
i am unsure which issue you encountered when trying to publish your package to hex.

**Comment by zmstone** [comment]
close this issue as it's already resolved in #209 , thank your for the pr anyways, and sorry for the delay

**Comment by rhblind** [comment]
Hi @zmstone 
Yes, sorry my mistake. It seems like maybe the `gun` version is somehow the problem. But I don't really understand why it's complaining about `emqtt 1.2.3`. I'm getting an error like this.

```
Resolving Hex dependencies...
Resolution completed in 0.397s
Because emqtt >= 1.2.3 depends on gun 1.3.3 which depends on cowlib ~> 2.7.0, emqtt >= 1.2.3 requires cowlib ~> 2.7.0.
And because your app depends on cowlib ~> 2.12, emqtt >= 1.2.3 is forbidden.
So, because your app depends on emqtt ~> 1.11, version solving failed.
```

**Pull request closed without merging**
